// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WoC.Fit.Backend.Data.Migrations
{
    [DbContext(typeof(NutriContext))]
    [Migration("20231009041259_Seed_Database")]
    partial class Seed_Database
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PortionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PortionType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Gramos"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mililitros"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pieza"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Rebanada"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cucharada"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Taza"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Cucharadita"
                        });
                });

            modelBuilder.Entity("WoC.Fit.Backend.Data.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "HEB"
                        },
                        new
                        {
                            Id = 2,
                            Name = "SCIFIT"
                        },
                        new
                        {
                            Id = 3,
                            Name = "ALLMAX"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Wellthy"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Lysi"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Menissez"
                        },
                        new
                        {
                            Id = 7,
                            Name = "KIRKLAND"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Columbus"
                        });
                });

            modelBuilder.Entity("WoC.Fit.Backend.Data.Models.Macronutrient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Macronutrients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Proteina"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Grasas"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Carbohidratos"
                        });
                });

            modelBuilder.Entity("WoC.Fit.Backend.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<double>("Calories")
                        .HasColumnType("float");

                    b.Property<double>("Carbohydrates")
                        .HasColumnType("float");

                    b.Property<double>("Fats")
                        .HasColumnType("float");

                    b.Property<int>("MacronutrientId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Portion")
                        .HasColumnType("float");

                    b.Property<int>("PortionTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<double>("Protein")
                        .HasColumnType("float");

                    b.Property<double>("Sodium")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("MacronutrientId");

                    b.HasIndex("PortionTypeId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            Calories = 110.0,
                            Carbohydrates = 1.3,
                            Fats = 0.51000000000000001,
                            MacronutrientId = 1,
                            Name = "Whey Protein Vainilla",
                            Portion = 31.300000000000001,
                            PortionTypeId = 1,
                            ProductTypeId = 1,
                            Protein = 25.0,
                            Sodium = 104.86
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 2,
                            Calories = 119.59999999999999,
                            Carbohydrates = 5.0,
                            Fats = 0.40000000000000002,
                            MacronutrientId = 1,
                            Name = "Whey Protein FrutiCereal",
                            Portion = 24.0,
                            PortionTypeId = 1,
                            ProductTypeId = 1,
                            Protein = 24.0,
                            Sodium = 119.0
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 3,
                            Calories = 130.0,
                            Carbohydrates = 4.0,
                            Fats = 2.0,
                            MacronutrientId = 1,
                            Name = "Whey Protein PeanutButter",
                            Portion = 32.0,
                            PortionTypeId = 1,
                            ProductTypeId = 1,
                            Protein = 24.0,
                            Sodium = 130.0
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 3,
                            Calories = 130.0,
                            Carbohydrates = 4.0,
                            Fats = 2.0,
                            MacronutrientId = 1,
                            Name = "Whey Protein Cookies & Cream",
                            Portion = 32.0,
                            PortionTypeId = 1,
                            ProductTypeId = 1,
                            Protein = 24.0,
                            Sodium = 150.0
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 4,
                            Calories = 124.0,
                            Carbohydrates = 0.0,
                            Fats = 0.59999999999999998,
                            MacronutrientId = 1,
                            Name = "Peas Protein",
                            Portion = 26.0,
                            PortionTypeId = 1,
                            ProductTypeId = 1,
                            Protein = 26.0,
                            Sodium = 53.0
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 5,
                            Calories = 42.0,
                            Carbohydrates = 0.0,
                            Fats = 4.5999999999999996,
                            MacronutrientId = 2,
                            Name = "Aceite de Pescado",
                            Portion = 5.0,
                            PortionTypeId = 2,
                            ProductTypeId = 8,
                            Protein = 0.0,
                            Sodium = 0.0
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 1,
                            Calories = 89.0,
                            Carbohydrates = 23.0,
                            Fats = 0.29999999999999999,
                            MacronutrientId = 3,
                            Name = "Banana",
                            Portion = 100.0,
                            PortionTypeId = 1,
                            ProductTypeId = 3,
                            Protein = 1.1000000000000001,
                            Sodium = 1.0
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 1,
                            Calories = 122.0,
                            Carbohydrates = 30.0,
                            Fats = 0.20000000000000001,
                            MacronutrientId = 3,
                            Name = "Pera Asiatica",
                            Portion = 210.0,
                            PortionTypeId = 1,
                            ProductTypeId = 3,
                            Protein = 1.0,
                            Sodium = 0.0
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 1,
                            Calories = 210.0,
                            Carbohydrates = 0.0,
                            Fats = 12.0,
                            MacronutrientId = 1,
                            Name = "Diezmillo",
                            Portion = 100.0,
                            PortionTypeId = 1,
                            ProductTypeId = 4,
                            Protein = 21.0,
                            Sodium = 65.0
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 1,
                            Calories = 155.0,
                            Carbohydrates = 0.0,
                            Fats = 7.0,
                            MacronutrientId = 1,
                            Name = "Top Sirlon",
                            Portion = 100.0,
                            PortionTypeId = 1,
                            ProductTypeId = 4,
                            Protein = 22.0,
                            Sodium = 56.0
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 1,
                            Calories = 149.0,
                            Carbohydrates = 0.0,
                            Fats = 7.4000000000000004,
                            MacronutrientId = 1,
                            Name = "Aguja Nortena",
                            Portion = 100.0,
                            PortionTypeId = 1,
                            ProductTypeId = 4,
                            Protein = 19.300000000000001,
                            Sodium = 60.0
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 1,
                            Calories = 165.0,
                            Carbohydrates = 0.0,
                            Fats = 3.6000000000000001,
                            MacronutrientId = 1,
                            Name = "Pechuga de Pollo",
                            Portion = 100.0,
                            PortionTypeId = 1,
                            ProductTypeId = 4,
                            Protein = 31.0,
                            Sodium = 65.0
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 1,
                            Calories = 65.0,
                            Carbohydrates = 0.34000000000000002,
                            Fats = 4.3700000000000001,
                            MacronutrientId = 1,
                            Name = "Huevo Mediano",
                            Portion = 1.0,
                            PortionTypeId = 3,
                            ProductTypeId = 5,
                            Protein = 5.54,
                            Sodium = 70.0
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 1,
                            Calories = 74.0,
                            Carbohydrates = 0.38,
                            Fats = 4.9699999999999998,
                            MacronutrientId = 1,
                            Name = "Huevo Grande",
                            Portion = 1.0,
                            PortionTypeId = 3,
                            ProductTypeId = 5,
                            Protein = 6.29,
                            Sodium = 80.0
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 1,
                            Calories = 90.0,
                            Carbohydrates = 16.0,
                            Fats = 2.5,
                            MacronutrientId = 3,
                            Name = "Leche de Almendras Vainilla",
                            Portion = 240.0,
                            PortionTypeId = 2,
                            ProductTypeId = 6,
                            Protein = 1.0,
                            Sodium = 150.0
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 1,
                            Calories = 110.0,
                            Carbohydrates = 23.0,
                            Fats = 2.5,
                            MacronutrientId = 3,
                            Name = "Leche de Almendras Chocolate",
                            Portion = 240.0,
                            PortionTypeId = 2,
                            ProductTypeId = 6,
                            Protein = 1.0,
                            Sodium = 230.0
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 6,
                            Calories = 233.0,
                            Carbohydrates = 49.0,
                            Fats = 1.0,
                            MacronutrientId = 3,
                            Name = "Mini Bolillo",
                            Portion = 100.0,
                            PortionTypeId = 1,
                            ProductTypeId = 7,
                            Protein = 7.0,
                            Sodium = 490.0
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 7,
                            Calories = 828.0,
                            Carbohydrates = 0.0,
                            Fats = 92.0,
                            MacronutrientId = 2,
                            Name = "Aceite de Semilla de Uva",
                            Portion = 100.0,
                            PortionTypeId = 2,
                            ProductTypeId = 8,
                            Protein = 0.0,
                            Sodium = 0.0
                        },
                        new
                        {
                            Id = 19,
                            BrandId = 8,
                            Calories = 105.0,
                            Carbohydrates = 1.0,
                            Fats = 1.0,
                            MacronutrientId = 1,
                            Name = "Pechuga de Pavo",
                            Portion = 100.0,
                            PortionTypeId = 1,
                            ProductTypeId = 4,
                            Protein = 23.0,
                            Sodium = 406.0
                        });
                });

            modelBuilder.Entity("WoC.Fit.Backend.Data.Models.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Suplemento Proteico"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Suplemento Nutricional"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fruta"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Carne"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Huevo"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Leche Vegetal"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Panadería"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Aceite"
                        });
                });

            modelBuilder.Entity("WoC.Fit.Backend.Data.Models.Product", b =>
                {
                    b.HasOne("WoC.Fit.Backend.Data.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoC.Fit.Backend.Data.Models.Macronutrient", "MainMacronutrient")
                        .WithMany("Products")
                        .HasForeignKey("MacronutrientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortionType", "PortionType")
                        .WithMany("Products")
                        .HasForeignKey("PortionTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WoC.Fit.Backend.Data.Models.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("MainMacronutrient");

                    b.Navigation("PortionType");

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("PortionType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WoC.Fit.Backend.Data.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WoC.Fit.Backend.Data.Models.Macronutrient", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WoC.Fit.Backend.Data.Models.ProductType", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
